apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pengy-bot-dev
  name: pengy-bot-dev-deployment
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pengy-bot-dev
  strategy:
    rollingUpdate:
      maxSurge: 0%
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pengy-bot-dev
    spec:
      nodeSelector:
        cloud.google.com/gke-spot: "true"
      containers:
      - image: asia-southeast1-docker.pkg.dev/blueee/blueee/pengy-bot-dev:placeholder
        imagePullPolicy: IfNotPresent
        name: app
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 1000m
            ephemeral-storage: 1Gi
            memory: 1Gi
          requests:
            cpu: 1000m
            ephemeral-storage: 1Gi
            memory: 1Gi
        securityContext:
          capabilities:
            drop:
            - NET_RAW
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: kubernetes.io/arch
        operator: Equal
        value: amd64