apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: pengy-bot
profiles:
  - name: dev
    build:
      artifacts:
        - image: asia-southeast1-docker.pkg.dev/blueee/blueee/pengy-bot-dev
          docker:
            dockerfile: Dockerfile
            buildArgs:
              START: start
    manifests:
      rawYaml:
        - deployment-dev.yaml
  - name: prod
    build:
      artifacts:
        - image: asia-southeast1-docker.pkg.dev/blueee/blueee/pengy-bot-prod
          docker:
            dockerfile: Dockerfile
            buildArgs:
              START: start:prod
    manifests:
      rawYaml:
        - deployment-prod.yaml